### ISSUE TITLE
Sample 64M R2 Question

### ISSUE THREAD

**Issue by adowneywall** [RobertsLab/project-oyster-comparative-omics#1]
Hi Yaamini and Steve,
I am working with the [adult methylation tissues](https://github.com/RobertsLab/project-oyster-comparative-omics/blob/master/metadata/zr4060_md5.csv) from the intergenerational Eastern oyster exposure and I noticed that the file for `64M_R2_val_2.fq.gz` was significantly smaller (~2.2Gb) compared to all the other samples [Link](http://owl.fish.washington.edu/nightingales/C_virginica/). I just wanted to confirm this file sequenced poorly compared to other samples and this wasn't some partial transfer issue. If it is not a transfer issue, I would be interested to get your thoughts on the best way to perform the mapping step for this sample since R1 file appears to contain significantly more reads. Would it be better to perform the mapping step using just the R1 file with the single-end flag?

**Comment by kubu4** [comment]
> and this wasn't some partial transfer issue

You should confirm transfers completed successfully by generating (and comparing) MD5 chekcsums for all of the files. Here are the checksums for these two files:

```
d117b3a4c4a406ae5e60ef4033cea972  64M_R1_val_1.fq.gz
ce1d4d9ffab8d2c485eb3e50bdd42611  64M_R2_val_2.fq.gz
```

If the MD5 checksums you generate _don't_ match those listed above, then you'll need to re-transfer them.

If they do match, then those files are fine. Then, we'd want to ask @yaaminiv what the sequencing details of the project were (specifically, was there a guaranteed minimum number of reads/bases for each sample; or, if it was a minimum number of bases/reads for the entire project; and, what Zymo's stance is on "acceptable" differences in read numbers across libraries).

EDITED: fixed typos

**Comment by kubu4** [comment]
Aaand, now that I've said all that, I see this same drastic difference in file size on our end. I'll look into it and report back soon.

**Comment by kubu4** [comment]
Okay, I've verified that the file is incomplete on our end. 

So sorry about the trouble and great catch!

I hadn't fully completed QC on these files (although, I probably should've done so by now).

I'll post here in a bit once the file is re-downloaded (and checksum confirmed) and available for you.

Again, very sorry about this!

**Comment by kubu4** [comment]
Also, here's the list of md5 checksums supplied by the sequencing facility. This will allow you to check the existing files on your end now, while you wait for me to confirm things over here:

```
fbba1de44336a39de7dea80761d4158 12M_R1_val_1.fq.gz
3b294ab8cef54b0b5b34e454691b87a4 12M_R2_val_2.fq.gz
07348c7e1a921eaf953a5bf858b7ab20 13M_R1_val_1.fq.gz
0126a23547ea69bad16af6da66c7dbcc 13M_R2_val_2.fq.gz
641082c9611849191f940ca89233bd02 16F_R1_val_1.fq.gz
2426970f40d9263672c76f0d5ba751ea 16F_R2_val_2.fq.gz
e581b09825d1a2e16ab0bb41a147b3db 19F_R1_val_1.fq.gz
0bfb87efe849a4ca50d279a47486b3ba 19F_R2_val_2.fq.gz
19d761d4390921218d32958f7bf96c41 22F_R1_val_1.fq.gz
2445220355ff3cb6562e924883c442f2 22F_R2_val_2.fq.gz
8cd5c26d8b6cb0e2758b082d4b369c1f 23M_R1_val_1.fq.gz
35c6efe68e49432ecd18aa2be1bc4f1b 23M_R2_val_2.fq.gz
d61e43ce7f88cd1a21858537a8da6ea5 29F_R1_val_1.fq.gz
316f6850a5720178d69d4807b5b07918 29F_R2_val_2.fq.gz
84faae234c032717c4cb183c6617be29 31M_R1_val_1.fq.gz
dd209c4755f18a07436edf350cc7d292 31M_R2_val_2.fq.gz
88e30cf70630f0e9c50f1200b167ef1b 35F_R1_val_1.fq.gz
084bc0f0f8777c1b177b140a49365b92 35F_R2_val_2.fq.gz
1b56a3612885d48a52f9bec7120d37a3 36F_R1_val_1.fq.gz
659036d612b6ed9303b49f745687a8cd 36F_R2_val_2.fq.gz
4fae5a42eea8a2f4e90bbd887f15219f 39F_R1_val_1.fq.gz
6318ce9b4b156cd4c0833b7049bb8ea9 39F_R2_val_2.fq.gz
de6d282d7eeccb47b9a4ad3c55f24e00 3F_R1_val_1.fq.gz
a5ad33bc4b80221270ffc039d3b69f23 3F_R2_val_2.fq.gz
5e559b56be0385589a48336f81828715 41F_R1_val_1.fq.gz
1dedbb07308fe90995379cccd69920c1 41F_R2_val_2.fq.gz
d4610e6e9fe14c47b063707aae56519d 44F_R1_val_1.fq.gz
fc9b74aac62d18eb313c9d0851399f05 44F_R2_val_2.fq.gz
17b85ab20b28d6b140cb8523eae969da 48M_R1_val_1.fq.gz
e56b32b0542c1586cd7fceebe7139925 48M_R2_val_2.fq.gz
15158b0aa8d0c9daecdf8714b4c44390 50F_R1_val_1.fq.gz
59cc3e97537b7f5651ed292d1bf08afa 50F_R2_val_2.fq.gz
bca3cc665b1ad9cfe5e85055031eb07f 52F_R1_val_1.fq.gz
588319f43f59bb3392932076677966c3 52F_R2_val_2.fq.gz
732e3a59d0c74c8b0c8be6c117a8128d 53F_R1_val_1.fq.gz
c073b7d16261f98e1885d69bdff1c60b 53F_R2_val_2.fq.gz
3654b40bb7bf1f6cf50169f61a4916d1 54F_R1_val_1.fq.gz
6bf9f53a97fec26cb126f80c2effa37e 54F_R2_val_2.fq.gz
69915585ac2b6a078084586ab848dcd3 59M_R1_val_1.fq.gz
ffde2fa5bcd8820ee3985b37d9024546 59M_R2_val_2.fq.gz
d117b3a4c4a406ae5e60ef4033cea972 64M_R1_val_1.fq.gz
974d4208427065278fee3ff53e923459 64M_R2_val_2.fq.gz
b6e26c14f460b4bfe9589784e7a2d1cf 6M_R1_val_1.fq.gz
2faf190670332df10ae4fc9e802542ac 6M_R2_val_2.fq.gz
566797d8e9b22dc8a58be98180daefdc 76F_R1_val_1.fq.gz
881d571b3c31e2ee48d4b4cd0c2ca8de 76F_R2_val_2.fq.gz
339163b4b0c8e1808eabc4ae2488c10c 77F_R1_val_1.fq.gz
ab5b2d87c2f5d2a4d3ce04951c315ec6 77F_R2_val_2.fq.gz
530bb553d2cdb898cda7e0c1f3611e17 7M_R1_val_1.fq.gz
c1e74de3c89833ffe443c4833ada7999 7M_R2_val_2.fq.gz
66f503dfea8582eeffde6ed7316cef3f 9M_R1_val_1.fq.gz
89d3e3071e75960834df0e09ddfc9cfe 9M_R2_val_2.fq.gz
```

**Comment by adowneywall** [comment]
Great! Thank you for looking into this so quickly!

**Comment by kubu4** [comment]
Alrighty, all files have been checked as good. I suspect that one was the only problem file. You can download directly from here:

https://owl.fish.washington.edu/nightingales/C_virginica/64M_R2_val_2.fq.gz

However, you should independently compare the checksums on your end before making any assumptions.

Again, terribly sorry I hadn't gotten around to checking these earlier like I should have!

![image](https://user-images.githubusercontent.com/4514104/123555427-81c24680-d73a-11eb-970b-af81a0caf87f.png)

**Comment by adowneywall** [comment]
Not a problem. Downloaded and checked the file on my end. Thanks again!
